version: "3.7"
services:
  web:
    container_name: dev_backend
    build:
      dockerfile: Dockerfile
    restart: always
    env_file: dev.env
    command: gunicorn trk.wsgi:application --bind 0.0.0.0:5000
    volumes:
      - .:/app
      - static_volume:/app/static
volumes:
  static_volume:
  postgres_data:
