# Generated by Django 4.0.3 on 2022-05-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunniplaan', '0002_classes_remove_class_name_alter_class_head_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='classes',
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
