# Generated by Django 4.0.3 on 2022-05-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunniplaan', '0003_remove_class_classes_class_name_delete_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(choices=[('5a', '5A'), ('5b', '5B'), ('6a', '6B'), ('6b', '6B'), ('7a', '7A'), ('7b', '7B'), ('7c', '7C'), ('8a', '8A'), ('8b', '8B'), ('8c', '8C'), ('9a', '9A'), ('9b', '9B'), ('9c', '9C'), ('10a', '10A'), ('10b', '10B'), ('10c', '10C'), ('11a', '11A'), ('11b', '11B'), ('11c', '11C'), ('12a', '12A'), ('12b', '12B'), ('12c', '12C')], default='8c', max_length=3),
        ),
    ]
