# Generated by Django 4.0.3 on 2022-05-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunniplaan', '0004_alter_class_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='ClassModel',
        ),
    ]
