# Generated by Django 4.0.3 on 2022-03-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_description',
            field=models.CharField(default='Sellele küsimusele täpsustusi pole.', max_length=200),
        ),
    ]
