FROM python:3.8.5-alpine

RUN python -m pip install --upgrade pip
RUN apk update
RUN apk add make automake gcc g++ subversion python3-dev

COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY ./trk /app

WORKDIR /app

COPY ./entrypoint.sh /
ENTRYPOINT ["sh", "/entrypoint.sh"]