version: "3.7"

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8020:8020"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "8080:8080"
    depends_on:
      - django_gunicorn

volumes:
  static:
